
// This file has been generated by the GUI designer. Do not modify.
namespace MultiCalc
{
	public partial class inversePolishNotation
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label1;
		private global::Gtk.Entry entry1;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label Label2;
		private global::Gtk.Entry entry2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox4;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Button buttonPlus;
		private global::Gtk.Button buttonMinus;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Button buttonMultiply;
		private global::Gtk.Button buttonDivide;
		private global::Gtk.Button buttonModulus;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label3;
		private global::Gtk.Entry entry3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MultiCalc.inversePolishNotation
			this.Name = "MultiCalc.inversePolishNotation";
			this.Title = global::Mono.Unix.Catalog.GetString ("inversePolishNotation");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MultiCalc.inversePolishNotation.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Input 2");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry1]));
			w2.Position = 1;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.Label2 = new global::Gtk.Label ();
			this.Label2.Name = "Label2";
			this.Label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Input 2");
			this.hbox5.Add (this.Label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.Label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.hbox5.Add (this.entry2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entry2]));
			w5.Position = 1;
			this.vbox5.Add (this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox5]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox3.Add (this.vbox5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonPlus = new global::Gtk.Button ();
			this.buttonPlus.CanFocus = true;
			this.buttonPlus.Name = "buttonPlus";
			this.buttonPlus.UseUnderline = true;
			this.buttonPlus.Label = global::Mono.Unix.Catalog.GetString ("+");
			this.hbox7.Add (this.buttonPlus);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonPlus]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonMinus = new global::Gtk.Button ();
			this.buttonMinus.CanFocus = true;
			this.buttonMinus.Name = "buttonMinus";
			this.buttonMinus.UseUnderline = true;
			this.buttonMinus.Label = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox7.Add (this.buttonMinus);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonMinus]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox7]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonMultiply = new global::Gtk.Button ();
			this.buttonMultiply.CanFocus = true;
			this.buttonMultiply.Name = "buttonMultiply";
			this.buttonMultiply.UseUnderline = true;
			this.buttonMultiply.Label = global::Mono.Unix.Catalog.GetString ("*");
			this.hbox6.Add (this.buttonMultiply);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonMultiply]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonDivide = new global::Gtk.Button ();
			this.buttonDivide.CanFocus = true;
			this.buttonDivide.Name = "buttonDivide";
			this.buttonDivide.UseUnderline = true;
			this.buttonDivide.Label = global::Mono.Unix.Catalog.GetString ("/");
			this.hbox6.Add (this.buttonDivide);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonDivide]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonModulus = new global::Gtk.Button ();
			this.buttonModulus.CanFocus = true;
			this.buttonModulus.Name = "buttonModulus";
			this.buttonModulus.UseUnderline = true;
			this.buttonModulus.Label = global::Mono.Unix.Catalog.GetString ("%");
			this.hbox6.Add (this.buttonModulus);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.buttonModulus]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox6]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Output");
			this.hbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.hbox3.Add (this.entry3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry3]));
			w17.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 409;
			this.DefaultHeight = 300;
			this.Show ();
			this.buttonPlus.Clicked += new global::System.EventHandler (this.OnButtonPlusClicked);
			this.buttonMinus.Clicked += new global::System.EventHandler (this.OnButtonMinusClicked);
			this.buttonMultiply.Clicked += new global::System.EventHandler (this.OnButtonMultiplyClicked);
			this.buttonDivide.Clicked += new global::System.EventHandler (this.OnButtonDivideClicked);
			this.buttonModulus.Clicked += new global::System.EventHandler (this.OnButtonModulusClicked);
		}
	}
}
