
// This file has been generated by the GUI designer. Do not modify.
namespace MultiCalc
{
	public partial class TempConvWindow
	{
		private global::Gtk.VBox vbox12;
		private global::Gtk.VBox vbox14;
		private global::Gtk.VBox vbox15;
		private global::Gtk.HBox hbox16;
		private global::Gtk.Label label23;
		private global::Gtk.Entry entryCelsius;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Label label24;
		private global::Gtk.Label labelFahrenheit;
		private global::Gtk.HBox hbox18;
		private global::Gtk.Button buttonCalc1;
		private global::Gtk.Button buttonClear1;
		private global::Gtk.VBox vbox13;
		private global::Gtk.VBox vbox16;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Label label25;
		private global::Gtk.Label labelCelsius;
		private global::Gtk.HBox hbox20;
		private global::Gtk.Label label26;
		private global::Gtk.Entry entryFahrenheit;
		private global::Gtk.HBox hbox21;
		private global::Gtk.Button buttonCalc2;
		private global::Gtk.Button buttonClear2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MultiCalc.TempConvWindow
			this.Name = "MultiCalc.TempConvWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TempConvWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MultiCalc.TempConvWindow.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Celsius (C): ");
			this.hbox16.Add (this.label23);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label23]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.entryCelsius = new global::Gtk.Entry ();
			this.entryCelsius.CanFocus = true;
			this.entryCelsius.Name = "entryCelsius";
			this.entryCelsius.IsEditable = true;
			this.entryCelsius.InvisibleChar = '●';
			this.hbox16.Add (this.entryCelsius);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.entryCelsius]));
			w2.Position = 1;
			this.vbox15.Add (this.hbox16);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox16]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Fahrenheit (F): ");
			this.hbox17.Add (this.label24);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label24]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.labelFahrenheit = new global::Gtk.Label ();
			this.labelFahrenheit.Name = "labelFahrenheit";
			this.hbox17.Add (this.labelFahrenheit);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.labelFahrenheit]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox15.Add (this.hbox17);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox17]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.buttonCalc1 = new global::Gtk.Button ();
			this.buttonCalc1.CanFocus = true;
			this.buttonCalc1.Name = "buttonCalc1";
			this.buttonCalc1.UseUnderline = true;
			this.buttonCalc1.Label = global::Mono.Unix.Catalog.GetString ("Calculate !");
			this.hbox18.Add (this.buttonCalc1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.buttonCalc1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.buttonClear1 = new global::Gtk.Button ();
			this.buttonClear1.CanFocus = true;
			this.buttonClear1.Name = "buttonClear1";
			this.buttonClear1.UseUnderline = true;
			this.buttonClear1.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox18.Add (this.buttonClear1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.buttonClear1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox15.Add (this.hbox18);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox18]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox14.Add (this.vbox15);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.vbox15]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox12.Add (this.vbox14);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.vbox14]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Celsius (C): ");
			this.hbox19.Add (this.label25);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label25]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.labelCelsius = new global::Gtk.Label ();
			this.labelCelsius.Name = "labelCelsius";
			this.hbox19.Add (this.labelCelsius);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.labelCelsius]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox16.Add (this.hbox19);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbox19]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Fahrenheit (F): ");
			this.hbox20.Add (this.label26);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label26]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.entryFahrenheit = new global::Gtk.Entry ();
			this.entryFahrenheit.CanFocus = true;
			this.entryFahrenheit.Name = "entryFahrenheit";
			this.entryFahrenheit.IsEditable = true;
			this.entryFahrenheit.InvisibleChar = '●';
			this.hbox20.Add (this.entryFahrenheit);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.entryFahrenheit]));
			w16.Position = 1;
			this.vbox16.Add (this.hbox20);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbox20]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.buttonCalc2 = new global::Gtk.Button ();
			this.buttonCalc2.CanFocus = true;
			this.buttonCalc2.Name = "buttonCalc2";
			this.buttonCalc2.UseUnderline = true;
			this.buttonCalc2.Label = global::Mono.Unix.Catalog.GetString ("Calculate !");
			this.hbox21.Add (this.buttonCalc2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.buttonCalc2]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.buttonClear2 = new global::Gtk.Button ();
			this.buttonClear2.CanFocus = true;
			this.buttonClear2.Name = "buttonClear2";
			this.buttonClear2.UseUnderline = true;
			this.buttonClear2.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox21.Add (this.buttonClear2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.buttonClear2]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox16.Add (this.hbox21);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.hbox21]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox13.Add (this.vbox16);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox16]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox12.Add (this.vbox13);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.vbox13]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox12);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.buttonCalc1.Clicked += new global::System.EventHandler (this.OnButtonCalc1Clicked);
			this.buttonClear1.Clicked += new global::System.EventHandler (this.OnButtonClear1Clicked);
			this.buttonCalc2.Clicked += new global::System.EventHandler (this.OnButtonCalc2Clicked);
			this.buttonClear2.Clicked += new global::System.EventHandler (this.OnButtonClear2Clicked);
		}
	}
}
