
// This file has been generated by the GUI designer. Do not modify.
namespace MultiCalc
{
	public partial class ConverterWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.VBox vbox8;
		private global::Gtk.VBox vbox9;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Label label12;
		private global::Gtk.Label labelCM3;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Label label32;
		private global::Gtk.Label labelM3;
		private global::Gtk.VBox vbox10;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label label14;
		private global::Gtk.Entry entryKM3;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Button buttonConvert3;
		private global::Gtk.Button buttonClear3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label7;
		private global::Gtk.Entry entryM2;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label8;
		private global::Gtk.Label labelM2;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label10;
		private global::Gtk.Label labelKM2;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Button buttonConvert2;
		private global::Gtk.Button buttonClear2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label labelCM;
		private global::Gtk.Entry entryCM;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label labelM;
		private global::Gtk.Label labelM1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label labelKM;
		private global::Gtk.Label labelKM1;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button buttonConvert;
		private global::Gtk.Button buttonClear;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MultiCalc.ConverterWindow
			this.Name = "MultiCalc.ConverterWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ConverterWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MultiCalc.ConverterWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Centimeters (cm): ");
			this.hbox13.Add (this.label12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label12]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.labelCM3 = new global::Gtk.Label ();
			this.labelCM3.Name = "labelCM3";
			this.hbox13.Add (this.labelCM3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.labelCM3]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox9.Add (this.hbox13);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox13]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Meters (m):");
			this.hbox12.Add (this.label32);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label32]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.labelM3 = new global::Gtk.Label ();
			this.labelM3.Name = "labelM3";
			this.hbox12.Add (this.labelM3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.labelM3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox9.Add (this.hbox12);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox12]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox8.Add (this.vbox9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox9]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Kilometers (km):");
			this.hbox11.Add (this.label14);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label14]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entryKM3 = new global::Gtk.Entry ();
			this.entryKM3.CanFocus = true;
			this.entryKM3.Name = "entryKM3";
			this.entryKM3.IsEditable = true;
			this.entryKM3.InvisibleChar = '●';
			this.hbox11.Add (this.entryKM3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.entryKM3]));
			w9.Position = 1;
			this.vbox10.Add (this.hbox11);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox11]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonConvert3 = new global::Gtk.Button ();
			this.buttonConvert3.CanFocus = true;
			this.buttonConvert3.Name = "buttonConvert3";
			this.buttonConvert3.UseUnderline = true;
			this.buttonConvert3.Label = global::Mono.Unix.Catalog.GetString ("Convert !");
			this.hbox10.Add (this.buttonConvert3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.buttonConvert3]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonClear3 = new global::Gtk.Button ();
			this.buttonClear3.CanFocus = true;
			this.buttonClear3.Name = "buttonClear3";
			this.buttonClear3.UseUnderline = true;
			this.buttonClear3.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox10.Add (this.buttonClear3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.buttonClear3]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox10.Add (this.hbox10);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox10]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox8.Add (this.vbox10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox10]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox4.Add (this.vbox8);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox8]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Meters (m):");
			this.hbox6.Add (this.label7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label7]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryM2 = new global::Gtk.Entry ();
			this.entryM2.CanFocus = true;
			this.entryM2.Name = "entryM2";
			this.entryM2.IsEditable = true;
			this.entryM2.InvisibleChar = '●';
			this.hbox6.Add (this.entryM2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entryM2]));
			w17.Position = 1;
			this.vbox6.Add (this.hbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Centimeters (cm):");
			this.hbox8.Add (this.label8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label8]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.labelM2 = new global::Gtk.Label ();
			this.labelM2.Name = "labelM2";
			this.hbox8.Add (this.labelM2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.labelM2]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox6.Add (this.hbox8);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox8]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox5.Add (this.vbox6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Kilometers (km):");
			this.hbox9.Add (this.label10);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label10]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.labelKM2 = new global::Gtk.Label ();
			this.labelKM2.Name = "labelKM2";
			this.hbox9.Add (this.labelKM2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.labelKM2]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox7.Add (this.hbox9);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox9]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonConvert2 = new global::Gtk.Button ();
			this.buttonConvert2.CanFocus = true;
			this.buttonConvert2.Name = "buttonConvert2";
			this.buttonConvert2.UseUnderline = true;
			this.buttonConvert2.Label = global::Mono.Unix.Catalog.GetString ("Convert !");
			this.hbox7.Add (this.buttonConvert2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonConvert2]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonClear2 = new global::Gtk.Button ();
			this.buttonClear2.CanFocus = true;
			this.buttonClear2.Name = "buttonClear2";
			this.buttonClear2.UseUnderline = true;
			this.buttonClear2.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox7.Add (this.buttonClear2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonClear2]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox7.Add (this.hbox7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox7]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox5.Add (this.vbox7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox7]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox5]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelCM = new global::Gtk.Label ();
			this.labelCM.Name = "labelCM";
			this.labelCM.LabelProp = global::Mono.Unix.Catalog.GetString ("Centimeters (cm):");
			this.hbox1.Add (this.labelCM);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labelCM]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryCM = new global::Gtk.Entry ();
			this.entryCM.CanFocus = true;
			this.entryCM.Name = "entryCM";
			this.entryCM.IsEditable = true;
			this.entryCM.InvisibleChar = '●';
			this.hbox1.Add (this.entryCM);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryCM]));
			w33.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelM = new global::Gtk.Label ();
			this.labelM.Name = "labelM";
			this.labelM.LabelProp = global::Mono.Unix.Catalog.GetString ("Meters (m):         ");
			this.hbox2.Add (this.labelM);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labelM]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelM1 = new global::Gtk.Label ();
			this.labelM1.Name = "labelM1";
			this.hbox2.Add (this.labelM1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labelM1]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelKM = new global::Gtk.Label ();
			this.labelKM.Name = "labelKM";
			this.labelKM.LabelProp = global::Mono.Unix.Catalog.GetString ("Kilometers (km): ");
			this.hbox5.Add (this.labelKM);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labelKM]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelKM1 = new global::Gtk.Label ();
			this.labelKM1.Name = "labelKM1";
			this.hbox5.Add (this.labelKM1);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labelKM1]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonConvert = new global::Gtk.Button ();
			this.buttonConvert.CanFocus = true;
			this.buttonConvert.Name = "buttonConvert";
			this.buttonConvert.UseUnderline = true;
			this.buttonConvert.Label = global::Mono.Unix.Catalog.GetString ("Convert !");
			this.hbox3.Add (this.buttonConvert);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonConvert]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonClear = new global::Gtk.Button ();
			this.buttonClear.CanFocus = true;
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox3.Add (this.buttonClear);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonClear]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 324;
			this.Show ();
			this.buttonConvert3.Clicked += new global::System.EventHandler (this.OnButtonConvert3Clicked);
			this.buttonClear3.Clicked += new global::System.EventHandler (this.OnButton11Clicked);
			this.buttonConvert2.Clicked += new global::System.EventHandler (this.OnButtonConvert2Clicked);
			this.buttonClear2.Clicked += new global::System.EventHandler (this.OnButtonClear2Clicked);
			this.buttonConvert.Clicked += new global::System.EventHandler (this.OnButtonConvertClicked);
			this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		}
	}
}
